"""Catalogul de semnale - sursa unică de adevăr.

Fiecare semnal este definit o singură dată, aici. Catalogul este expus prin
``GET /api/v1/signals``, iar frontendul își construiește cardurile, graficele și
pragurile din el. Adăugarea unui senzor nou înseamnă o linie în acest fișier și
zero modificări în React.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Literal

SignalGroup = Literal["status", "energy", "thermal", "motor", "gps", "chassis", "board"]


@dataclass(frozen=True, slots=True)
class Signal:
    """Definiția unui semnal de telemetrie.

    Pragurile sunt opționale. ``hysteresis`` este exprimat în unitatea
    semnalului și împiedică alarmele să pâlpâie când valoarea oscilează exact
    în jurul pragului: alarma se activează la prag, dar se stinge doar după ce
    valoarea revine cu ``hysteresis`` dincolo de el.
    """

    key: str
    label: str
    unit: str
    group: SignalGroup
    decimals: int = 1
    min: float | None = None
    max: float | None = None
    stale_after_s: float = 2.0
    warn_below: float | None = None
    crit_below: float | None = None
    warn_above: float | None = None
    crit_above: float | None = None
    hysteresis: float = 0.0
    # Semnalele „overview" apar pe pagina principală ca metric cards.
    overview: bool = False
    # Semnalele marcate pentru grafic sunt propuse implicit în selectorul de serii.
    chartable: bool = True
    # Culoare sugerată pentru serie (frontendul o poate ignora).
    color: str | None = None
    description: str = ""

    def to_dict(self) -> dict:
        return asdict(self)


CATALOG: tuple[Signal, ...] = (
    # --- Stare generală -----------------------------------------------------
    Signal(
        key="vehicle_speed_kph",
        label="Viteză",
        unit="km/h",
        group="status",
        decimals=1,
        min=0,
        max=140,
        overview=True,
        color="#60a5fa",
        description="Viteza la sol calculată de firmware din turația motorului și circumferința roții configurată pe placă.",
    ),
    Signal(
        key="lap_number",
        label="Tur",
        unit="",
        group="status",
        decimals=0,
        min=0,
        chartable=False,
        description="Numărul turului curent, calculat din trecerile prin start/finiș.",
    ),
    Signal(
        key="distance_km",
        label="Distanță",
        unit="km",
        group="status",
        decimals=2,
        min=0,
        description="Distanța totală parcursă în sesiune.",
    ),
    # --- Energie și baterie -------------------------------------------------
    Signal(
        key="battery_soc_pct",
        label="Stare baterie",
        unit="%",
        group="energy",
        decimals=1,
        min=0,
        max=100,
        warn_below=25,
        crit_below=15,
        hysteresis=2,
        overview=True,
        color="#34d399",
        description="Starea de încărcare estimată de BMS.",
    ),
    Signal(
        key="battery_voltage_v",
        label="Tensiune pachet",
        unit="V",
        group="energy",
        decimals=1,
        min=80,
        max=140,
        warn_below=94,
        crit_below=88,
        hysteresis=1,
        color="#a78bfa",
    ),
    Signal(
        key="battery_current_a",
        label="Curent pachet",
        unit="A",
        group="energy",
        decimals=1,
        min=-80,
        max=120,
        warn_above=75,
        crit_above=95,
        hysteresis=4,
        color="#f472b6",
        description="Pozitiv la descărcare, negativ la regenerare.",
    ),
    Signal(
        key="battery_power_w",
        label="Putere baterie",
        unit="W",
        group="energy",
        decimals=0,
        min=-8000,
        max=14000,
        color="#38bdf8",
        description="Puterea netă scoasă din pachet: sarcina minus aportul solar. Pozitivă la descărcare, negativă la încărcare.",
    ),
    Signal(
        key="cell_voltage_min_v",
        label="Celulă minimă",
        unit="V",
        group="energy",
        decimals=3,
        min=2.5,
        max=4.3,
        warn_below=3.0,
        crit_below=2.8,
        hysteresis=0.05,
        color="#fb7185",
    ),
    Signal(
        key="cell_voltage_max_v",
        label="Celulă maximă",
        unit="V",
        group="energy",
        decimals=3,
        min=2.5,
        max=4.3,
        warn_above=4.15,
        crit_above=4.22,
        hysteresis=0.03,
        color="#fbbf24",
    ),
    Signal(
        key="solar_power_w",
        label="Putere solară",
        unit="W",
        group="energy",
        decimals=0,
        min=0,
        max=1600,
        overview=True,
        color="#fbbf24",
        description="Puterea totală livrată de panouri prin controlerele MPPT.",
    ),
    # Mașina are două convertoare MPPT; `solar_power_w` este suma lor.
    Signal(key="mppt1_power_w", label="MPPT 1", unit="W", group="energy", decimals=0, min=0, max=450),
    Signal(key="mppt2_power_w", label="MPPT 2", unit="W", group="energy", decimals=0, min=0, max=450),
    Signal(
        key="energy_consumed_wh",
        label="Energie consumată",
        unit="Wh",
        group="energy",
        decimals=0,
        min=0,
        description="Energie scoasă din pachet de la începutul sesiunii.",
    ),
    Signal(
        key="energy_regen_wh",
        label="Energie regenerată",
        unit="Wh",
        group="energy",
        decimals=0,
        min=0,
        description="Energie intrată în pachet de la începutul sesiunii: frână regenerativă și surplus solar.",
    ),
    Signal(
        key="energy_solar_wh",
        label="Energie solară",
        unit="Wh",
        group="energy",
        decimals=0,
        min=0,
    ),
    # --- Temperaturi --------------------------------------------------------
    Signal(
        key="battery_temp_max_c",
        label="Temp. baterie max.",
        unit="°C",
        group="thermal",
        decimals=1,
        min=-10,
        max=80,
        warn_above=50,
        crit_above=60,
        hysteresis=3,
        overview=True,
        color="#f97316",
    ),
    Signal(
        key="battery_temp_min_c",
        label="Temp. baterie min.",
        unit="°C",
        group="thermal",
        decimals=1,
        min=-10,
        max=80,
    ),
    Signal(
        key="battery_temp_delta_c",
        label="Delta temp. celule",
        unit="°C",
        group="thermal",
        decimals=1,
        min=0,
        max=25,
        warn_above=8,
        crit_above=12,
        hysteresis=1,
        color="#fb923c",
        description="Diferența dintre cea mai caldă și cea mai rece celulă.",
    ),
    Signal(
        key="motor_temp_c",
        label="Temp. motor",
        unit="°C",
        group="thermal",
        decimals=1,
        min=0,
        max=140,
        warn_above=90,
        crit_above=110,
        hysteresis=5,
        color="#ef4444",
    ),
    Signal(
        key="inverter_temp_c",
        label="Temp. invertor",
        unit="°C",
        group="thermal",
        decimals=1,
        min=0,
        max=110,
        warn_above=70,
        crit_above=85,
        hysteresis=4,
        color="#f59e0b",
    ),
    # --- Motor --------------------------------------------------------------
    Signal(
        key="motor_power_w",
        label="Putere motor",
        unit="W",
        group="motor",
        decimals=0,
        min=-5000,
        max=14000,
        color="#60a5fa",
        description="Puterea cerută de motor (sarcina), înainte de scăderea aportului solar. Negativă la regenerare.",
    ),
    Signal(
        key="motor_rpm",
        label="Turație motor",
        unit="rpm",
        group="motor",
        decimals=0,
        min=0,
        max=1600,
    ),
    Signal(
        key="throttle_pct",
        label="Accelerație",
        unit="%",
        group="motor",
        decimals=0,
        min=0,
        max=100,
    ),
    # --- GPS ----------------------------------------------------------------
    Signal(
        key="gps_latitude_deg",
        label="Latitudine",
        unit="°",
        group="gps",
        decimals=6,
        stale_after_s=3.0,
        chartable=False,
    ),
    Signal(
        key="gps_longitude_deg",
        label="Longitudine",
        unit="°",
        group="gps",
        decimals=6,
        stale_after_s=3.0,
        chartable=False,
    ),
    Signal(
        key="gps_hdop",
        label="Precizie GPS (HDOP)",
        unit="",
        group="gps",
        decimals=2,
        min=0,
        max=20,
        warn_above=2.5,
        crit_above=5.0,
        hysteresis=0.4,
        stale_after_s=3.0,
        description="Valori mici înseamnă poziție mai precisă.",
    ),
    Signal(
        key="gps_satellites",
        label="Sateliți",
        unit="",
        group="gps",
        decimals=0,
        min=0,
        max=24,
        warn_below=6,
        crit_below=4,
        hysteresis=1,
        stale_after_s=3.0,
        chartable=False,
    ),
    # --- Semnale suplimentare -----------------------------------------------
    Signal(
        key="gps_altitude_m",
        label="Altitudine",
        unit="m",
        group="gps",
        decimals=1,
        min=-100,
        max=3000,
        stale_after_s=3.0,
        color="#94a3b8",
        description="Elevația deasupra elipsoidului WGS84, folosită pentru profilul de traseu.",
    ),
    Signal(
        key="gps_speed_kph",
        label="Viteză GPS",
        unit="km/h",
        group="gps",
        decimals=1,
        min=0,
        max=140,
        stale_after_s=3.0,
        color="#7dd3fc",
        description="Viteza la sol calculată de receptorul GNSS, independentă de senzorul de roată.",
    ),
    Signal(
        key="gps_course_deg",
        label="Direcție",
        unit="°",
        group="gps",
        decimals=1,
        min=0,
        max=360,
        stale_after_s=3.0,
        chartable=False,
        description="Cursul deasupra solului, 0° = nord.",
    ),
    Signal(
        key="gps_fix_quality",
        label="Calitate fix",
        unit="",
        group="gps",
        decimals=0,
        min=0,
        max=5,
        crit_below=1,
        stale_after_s=3.0,
        chartable=False,
        description="0 fără fix, 1 GPS, 2 DGPS, 4 RTK fix, 5 RTK float.",
    ),
    Signal(
        key="gps_vdop",
        label="Precizie verticală (VDOP)",
        unit="",
        group="gps",
        decimals=2,
        min=0,
        max=20,
        warn_above=3.5,
        crit_above=6.0,
        hysteresis=0.4,
        stale_after_s=3.0,
        description="Dispersia pe verticală; peste 3,5 altitudinea nu susține calculul de pantă.",
    ),
    # --- Baterie: capacitate, sănătate, celule individuale ------------------
    Signal(
        key="battery_capacity_remain_ah",
        label="Capacitate rămasă",
        unit="Ah",
        group="energy",
        decimals=2,
        min=0,
        max=200,
        description="Capacitatea rămasă raportată de BMS.",
    ),
    Signal(
        key="battery_capacity_total_ah",
        label="Capacitate învățată",
        unit="Ah",
        group="energy",
        decimals=2,
        min=0,
        max=200,
        chartable=False,
        description="Capacitatea totală învățată de BMS, nu cea de proiect.",
    ),
    Signal(
        key="battery_cycles",
        label="Cicluri",
        unit="",
        group="energy",
        decimals=0,
        min=0,
        max=10000,
        chartable=False,
        description="Numărul de cicluri complete numărate de BMS.",
    ),
    Signal(
        key="battery_soh_pct",
        label="Stare de sănătate",
        unit="%",
        group="energy",
        decimals=1,
        min=0,
        max=100,
        warn_below=85,
        crit_below=75,
        hysteresis=2,
        chartable=False,
        description="Raportată de BMS. Absentă pe BMS-urile care nu cunosc capacitatea de proiect.",
    ),
    Signal(
        key="cell_voltage_delta_v",
        label="Dezechilibru celule",
        unit="V",
        group="energy",
        decimals=3,
        min=0,
        max=1.0,
        warn_above=0.25,
        crit_above=0.35,
        hysteresis=0.03,
        color="#f87171",
        description="Diferența dintre celula maximă și cea minimă.",
    ),
    Signal(
        key="cell_min_index",
        label="Index celulă minimă",
        unit="",
        group="energy",
        decimals=0,
        min=0,
        max=32,
        chartable=False,
    ),
    Signal(
        key="cell_max_index",
        label="Index celulă maximă",
        unit="",
        group="energy",
        decimals=0,
        min=0,
        max=32,
        chartable=False,
    ),
    Signal(
        key="regen_power_w",
        label="Putere regenerată",
        unit="W",
        group="energy",
        decimals=0,
        min=0,
        max=8000,
        color="#4ade80",
        description="Puterea instantanee recuperată de frâna regenerativă în pachet.",
    ),
    # --- Tensiunea fiecărei celule din pachet -------------------------------
    Signal(key="cell_01_v", label="Celula 1", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_02_v", label="Celula 2", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_03_v", label="Celula 3", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_04_v", label="Celula 4", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_05_v", label="Celula 5", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_06_v", label="Celula 6", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_07_v", label="Celula 7", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_08_v", label="Celula 8", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_09_v", label="Celula 9", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_10_v", label="Celula 10", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_11_v", label="Celula 11", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_12_v", label="Celula 12", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_13_v", label="Celula 13", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_14_v", label="Celula 14", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_15_v", label="Celula 15", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_16_v", label="Celula 16", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_17_v", label="Celula 17", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_18_v", label="Celula 18", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_19_v", label="Celula 19", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_20_v", label="Celula 20", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_21_v", label="Celula 21", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_22_v", label="Celula 22", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_23_v", label="Celula 23", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_24_v", label="Celula 24", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_25_v", label="Celula 25", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_26_v", label="Celula 26", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_27_v", label="Celula 27", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_28_v", label="Celula 28", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_29_v", label="Celula 29", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_30_v", label="Celula 30", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_31_v", label="Celula 31", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    Signal(key="cell_32_v", label="Celula 32", unit="V", group="energy", decimals=3, min=2.5, max=4.3, warn_below=3.0, crit_below=2.8, warn_above=4.15, crit_above=4.22, hysteresis=0.03, chartable=False),
    # --- Motor: cadrele 0, 1 și 2 ale controllerului Mitsuba ----------------
    Signal(
        key="motor_current_peak_a",
        label="Curent de vârf motor",
        unit="A",
        group="motor",
        decimals=1,
        min=0,
        max=250,
        warn_above=180,
        crit_above=220,
        hysteresis=5,
        color="#fb7185",
    ),
    Signal(
        key="motor_pwm_duty_pct",
        label="PWM duty",
        unit="%",
        group="motor",
        decimals=1,
        min=0,
        max=100,
    ),
    Signal(
        key="motor_lead_angle_deg",
        label="Unghi de avans",
        unit="°",
        group="motor",
        decimals=1,
        min=0,
        max=60,
    ),
    Signal(
        key="regen_vr_pct",
        label="Potențiometru regen",
        unit="%",
        group="motor",
        decimals=0,
        min=0,
        max=100,
    ),
    Signal(
        key="motor_output_target",
        label="Țintă de ieșire",
        unit="",
        group="motor",
        decimals=0,
        min=0,
        max=255,
        chartable=False,
    ),
    Signal(
        key="drive_action",
        label="Acțiune",
        unit="",
        group="motor",
        decimals=0,
        min=0,
        max=3,
        chartable=False,
        description="0 oprit, 1 rezervat, 2 înainte, 3 marșarier.",
    ),
    Signal(
        key="power_mode",
        label="Mod de putere",
        unit="",
        group="motor",
        decimals=0,
        min=0,
        max=1,
        chartable=False,
        description="0 eco, 1 power.",
    ),
    Signal(
        key="motor_ctrl_mode",
        label="Mod de control",
        unit="",
        group="motor",
        decimals=0,
        min=0,
        max=1,
        chartable=False,
        description="0 control pe curent, 1 control pe PWM.",
    ),
    Signal(
        key="regen_active",
        label="Regenerare",
        unit="",
        group="motor",
        decimals=0,
        min=0,
        max=1,
        chartable=False,
        description="1 cât timp controllerul recuperează energie.",
    ),
    Signal(
        key="motor_overheat_level",
        label="Nivel supraîncălzire",
        unit="",
        group="motor",
        decimals=0,
        min=0,
        max=3,
        warn_above=0.5,
        crit_above=2.5,
        chartable=False,
        description="Treapta de limitare termică raportată de controller: 0 normal, 3 critic.",
    ),
    Signal(
        key="digi_sw_position",
        label="Comutator digital",
        unit="",
        group="motor",
        decimals=0,
        min=0,
        max=9,
        chartable=False,
    ),
    Signal(
        key="motor_fault_code",
        label="Cod de eroare controller",
        unit="",
        group="motor",
        decimals=0,
        chartable=False,
        description="Mască de biți din cadrul 2, descompusă pe nume în pagina Sistem.",
    ),
    # --- Senzori de temperatură pe mașină -----------------------------------
    Signal(
        key="temp_ambient_c",
        label="Temp. ambiantă",
        unit="°C",
        group="thermal",
        decimals=1,
        min=-20,
        max=60,
        color="#38bdf8",
        description="Aerul din afara caroseriei; referința pentru toate creșterile de temperatură.",
    ),
    Signal(
        key="temp_cockpit_c",
        label="Temp. habitaclu",
        unit="°C",
        group="thermal",
        decimals=1,
        min=-10,
        max=80,
        warn_above=45,
        crit_above=55,
        hysteresis=2,
    ),
    Signal(
        key="temp_pack_front_c",
        label="Temp. pachet față",
        unit="°C",
        group="thermal",
        decimals=1,
        min=-10,
        max=80,
        warn_above=50,
        crit_above=60,
        hysteresis=3,
    ),
    Signal(
        key="temp_pack_rear_c",
        label="Temp. pachet spate",
        unit="°C",
        group="thermal",
        decimals=1,
        min=-10,
        max=80,
        warn_above=50,
        crit_above=60,
        hysteresis=3,
    ),
    Signal(
        key="temp_mppt_c",
        label="Temp. MPPT",
        unit="°C",
        group="thermal",
        decimals=1,
        min=-10,
        max=100,
        warn_above=70,
        crit_above=85,
        hysteresis=3,
    ),
    # --- Șasiu: presiunea și temperatura anvelopelor ------------------------
    Signal(key="tpms_fl_pressure_bar", label="Presiune faţă stânga", unit="bar", group="chassis", decimals=2, min=0, max=6, warn_below=1.6, crit_below=1.3, warn_above=4.2, crit_above=4.6, hysteresis=0.05),
    Signal(key="tpms_fr_pressure_bar", label="Presiune faţă dreapta", unit="bar", group="chassis", decimals=2, min=0, max=6, warn_below=1.6, crit_below=1.3, warn_above=4.2, crit_above=4.6, hysteresis=0.05),
    Signal(key="tpms_rl_pressure_bar", label="Presiune spate stânga", unit="bar", group="chassis", decimals=2, min=0, max=6, warn_below=1.6, crit_below=1.3, warn_above=4.2, crit_above=4.6, hysteresis=0.05),
    Signal(key="tpms_rr_pressure_bar", label="Presiune spate dreapta", unit="bar", group="chassis", decimals=2, min=0, max=6, warn_below=1.6, crit_below=1.3, warn_above=4.2, crit_above=4.6, hysteresis=0.05),
    Signal(key="tpms_fl_temp_c", label="Temp. anvelopă faţă stânga", unit="°C", group="chassis", decimals=1, min=-10, max=120, warn_above=70, crit_above=85, hysteresis=3),
    Signal(key="tpms_fr_temp_c", label="Temp. anvelopă faţă dreapta", unit="°C", group="chassis", decimals=1, min=-10, max=120, warn_above=70, crit_above=85, hysteresis=3),
    Signal(key="tpms_rl_temp_c", label="Temp. anvelopă spate stânga", unit="°C", group="chassis", decimals=1, min=-10, max=120, warn_above=70, crit_above=85, hysteresis=3),
    Signal(key="tpms_rr_temp_c", label="Temp. anvelopă spate dreapta", unit="°C", group="chassis", decimals=1, min=-10, max=120, warn_above=70, crit_above=85, hysteresis=3),
    # --- Placa de achiziție Teensy ------------------------------------------
    Signal(
        key="teensy_temp_c",
        label="Temp. placă",
        unit="°C",
        group="board",
        decimals=1,
        min=0,
        max=100,
        warn_above=65,
        crit_above=80,
        hysteresis=3,
        description="Senzorul intern al plăcii de achiziție, nu al mașinii.",
    ),
    Signal(
        key="teensy_loop_hz",
        label="Ritm buclă",
        unit="Hz",
        group="board",
        decimals=0,
        min=0,
        max=2000,
        warn_below=80,
        crit_below=40,
        hysteresis=5,
        description="Câte cicluri complete execută firmware-ul pe secundă.",
    ),
    Signal(
        key="teensy_can_errors",
        label="Erori CAN",
        unit="",
        group="board",
        decimals=0,
        min=0,
        max=100000,
        description="Contor cumulativ de cadre CAN respinse de controller.",
    ),
    Signal(
        key="teensy_free_ram_kb",
        label="RAM liberă",
        unit="kB",
        group="board",
        decimals=0,
        min=0,
        max=1024,
        warn_below=32,
        crit_below=12,
        hysteresis=2,
    ),
    Signal(
        key="teensy_uptime_s",
        label="Uptime placă",
        unit="s",
        group="board",
        decimals=0,
        min=0,
        chartable=False,
        description="Se resetează la fiecare repornire a plăcii - util la depistarea reset-urilor.",
    ),
)

BY_KEY: dict[str, Signal] = {signal.key: signal for signal in CATALOG}

GROUP_LABELS: dict[str, str] = {
    "status": "Stare generală",
    "energy": "Energie și baterie",
    "thermal": "Temperaturi",
    "motor": "Motor",
    "gps": "Poziție",
    "chassis": "Șasiu și anvelope",
    "board": "Placă de achiziție",
}


def catalog_payload() -> dict:
    """Reprezentarea catalogului trimisă frontendului."""
    return {
        "signals": [signal.to_dict() for signal in CATALOG],
        "groups": [{"key": key, "label": label} for key, label in GROUP_LABELS.items()],
    }


@dataclass(frozen=True, slots=True)
class CompositeRule:
    """Regulă de alarmă care nu derivă dintr-un singur prag de semnal."""

    key: str
    label: str
    severity: Literal["critical", "warning", "info"]
    message: str
    signals: tuple[str, ...] = field(default=())


# Regulile compuse sunt evaluate în app/core/alarms.py.
COMPOSITE_RULES: tuple[CompositeRule, ...] = (
    CompositeRule(
        key="link_lost",
        label="Legătură pierdută",
        severity="critical",
        message="Nu s-au mai primit mesaje de la mașină.",
    ),
    CompositeRule(
        key="cell_imbalance",
        label="Dezechilibru celule",
        severity="warning",
        message="Diferența dintre celula minimă și cea maximă depășește 0,25 V.",
        signals=("cell_voltage_min_v", "cell_voltage_max_v"),
    ),
    CompositeRule(
        key="energy_deficit",
        label="Deficit de energie",
        severity="info",
        message="Consumul depășește de peste trei ori aportul solar.",
        signals=("battery_power_w", "solar_power_w"),
    ),
)
